/*-------------------------------------------------------------------
-- - Purpose : Structure class for Convention/Avenant specifics values
--
-- - Maintenance History:
--
-- Date        Name  Company     Version  Remarks
-- ----------  ----  ----------- -------  ----------------------------
-- XX/XX/20XX  T.CH  MODIS       1.0      Initial version
--------------------------------------------------------------------*/
public class SignatureStructure {
    public String fileTitle {get; set;}

    public String fileName {get; set;}

    public PageReference page {get; set;}
}